Repository pypa/pipenv, pull requests merged in 2018-05, with the labels that each got.

#2104 Backport `NamedTemporaryFile` for `io.open` support
  pipenv/_compat.py
  pipenv/core.py
  pipenv/utils.py
  tasks/vendoring/__init__.py
  tests/integration/conftest.py
Labels: ready to merge

#2111 Always use sources from Pipfile when doing resolution
  pipenv/resolver.py
  tests/integration/test_lock.py
Labels: ready to merge

#2052 Speed up lock by removing redundant freeze
  pipenv/core.py
Labels: enhancement, ready to merge

#2109 Fix whitespace in resolution failure hint
  pipenv/utils.py
Labels: enhancement, ready to merge

#2112 Update 2.7 default to 2.7.15
  pipenv/core.py
Labels: ready to merge

#2118 Normalize name when checking outdated packages
  pipenv/core.py
Labels: ready to merge

#2069 Default to \n, retain consistent \r\n
  pipenv/_compat.py
  pipenv/core.py
  pipenv/project.py
  pipenv/utils.py
  tests/integration/conftest.py
  tests/integration/test_project.py
Labels: enhancement, windows

#2135 Parse and include extras from vcs and non-vcs urls
  pipenv/utils.py
  tests/unit/test_utils.py
Labels: dependency resolution, vcs

#2163 Add a message to talk the user away from reporting
  pipenv/core.py
Labels: documentation, enhancement

#2167 Adds environment name to PROMPT on Cmd, Cmder,ConEmu
  pipenv/patched/pew/pew.py
  tasks/vendoring/patches/patched/pew-windows-env-name-in-prompt.patch
Labels: vendored dependencies, windows

#1861 Associate project dir with new virtual environment
  pipenv/core.py
Labels: ready to merge

#2142 Fix grouping of extras requirements in notpip
  pipenv/patched/notpip/index.py
  tasks/vendoring/patches/patched/pip.patch
  tests/unit/test_patched.py
Labels: bug 🐛, dependency resolution, regression
