Repository pypa/pipenv, pull requests merged in 2018-07, with the labels that each got.

#2458 Avoid double `pip` output if `--verbose` is used an output includes "Ignoring"
  pipenv/core.py
Labels: needs more information

#2300 Reduce image filesize for documentation
  docs/_static/pipenv.png
Labels: requires bdfl approval

#2605 fix grammar in error message
  pipenv/core.py
Labels: ready to merge

#2604 Exclude more things from installation which aren't meant to be installed
  setup.py
Labels: ready to merge

#2629 Add JSONDecodeError handling for get_lockfile_hash
  news/2607.bugfix
  pipenv/core.py
  pipenv/project.py
  tests/integration/test_lock.py
Labels: ready to merge

#2582 Dial back Pythonfinder integration effort
  news/2582.bugfix
  news/2582.feature
  news/2582.vendor
  pipenv/core.py
  pipenv/environments.py
  pipenv/help.py
  pipenv/vendor/README.md
  pipenv/vendor/cached-property.LICENSE
  pipenv/vendor/cached_property.py
  pipenv/vendor/pythonfinder/__init__.py
  pipenv/vendor/pythonfinder/_vendor/Makefile
  pipenv/vendor/pythonfinder/_vendor/vendor.txt
  pipenv/vendor/pythonfinder/exceptions.py
  pipenv/vendor/pythonfinder/models/__init__.py
  pipenv/vendor/pythonfinder/models/path.py
  pipenv/vendor/pythonfinder/models/pyenv.py
  pipenv/vendor/pythonfinder/models/python.py
  pipenv/vendor/pythonfinder/models/windows.py
  pipenv/vendor/pythonfinder/pythonfinder.py
  pipenv/vendor/pythonfinder/utils.py
  pipenv/vendor/vendor.txt
  run-tests.sh
  tasks/vendoring/__init__.py
Labels: ready to merge

#2643 Fix resolution using `dependency_links` with ssh
  news/2434.bugfix
  news/2643.bugfix
  news/2643.feature
  pipenv/patched/piptools/repositories/pypi.py
  pipenv/utils.py
  tasks/vendoring/patches/patched/piptools.patch
Labels: ready to merge

#2651 Use COMSPEC for shell detection fallback
  news/2651.behavior
  pipenv/environments.py
  pipenv/shells.py
Labels: ready to merge

#2646 Unify verbosity specification
  news/2527.feature
  pipenv/cli.py
  pipenv/core.py
  pipenv/environments.py
  pipenv/resolver.py
  pipenv/utils.py
Labels: ready to merge
