Repository pypa/pipenv, pull requests merged in 2018-03, with the labels that each got.

#1621 Shellquote all shell execs for path escaping
  pipenv/core.py
  pipenv/utils.py
  tests/test_utils.py
Labels: DO NOT MERGE

#1778 better cleanup_toml
  pipenv/utils.py
Labels: requires bdfl approval

#1769 Allow values in Pipfile to consume Environment Variables
  docs/advanced.rst
  pipenv/vendor/pipfile/api.py
  tests/test_vendor.py
Labels: requires bdfl approval

#1825 Add tests for environment marker precedence logic
  .travis.yml
  tests/test_pipenv.py
Labels: dependency resolution, enhancement

#1821 More documentation
  docs/diagnose.rst
Labels: documentation
