Repository pypa/pipenv, pull requests merged in 2018-04, with the labels that each got.

#1981 Fix jenkins tests
  pipenv/core.py
  pipenv/project.py
  pipenv/utils.py
  run-tests.sh
  tests/__init__.py
  tests/integration/__init__.py
  tests/unit/__init__.py
Labels: ready to merge

#1917 Make costly imports lazy to optimize startup time
  pipenv/cli.py
  pipenv/core.py
  pipenv/project.py
  pipenv/utils.py
  tests/integration/test_install_uri.py
Labels: enhancement

#1668 Prep for warehouse release (ETA: EOM)
  Pipfile.lock
  pipenv/patched/notpip/_vendor/distlib/index.py
  pipenv/patched/notpip/_vendor/distlib/locators.py
  pipenv/patched/notpip/index.py
  pipenv/patched/notpip/models/index.py
  pipenv/patched/pipfile/api.py
  pipenv/patched/piptools/repositories/pypi.py
  pipenv/project.py
  pipenv/vendor/pip9/_vendor/distlib/index.py
  pipenv/vendor/pip9/_vendor/distlib/locators.py
  pipenv/vendor/pip9/index.py
  pipenv/vendor/pip9/models/index.py
  tasks/vendoring/patches/patched/_post-pip-update-pypi-uri.patch
  tasks/vendoring/patches/patched/pipfile-update-pypi-uri.patch
  tasks/vendoring/patches/vendor/pip-update-pypi-uri.patch
Labels: future, requires bdfl approval

#2077 Atomic lockfile overwrite
  pipenv/core.py
  pipenv/project.py
  pipenv/utils.py
Labels: behavior change, enhancement, ready to merge

#1998 I believe this tox config is more correct this way
  docs/advanced.rst
Labels: documentation, enhancement, ready to merge

#2030 Fix progress.py to obey PIPENV_COLORBLIND and not use any colors.
  pipenv/core.py
  pipenv/progress.py
Labels: behavior change, enhancement, ready to merge

#2080 Allow pyenv installs in non-interactive sessions in PIPENV_YES is set
  pipenv/core.py
Labels: behavior change, enhancement, ready to merge
