Repository pypa/pipenv, pull requests merged in 2018-11, with the labels that each got.

#3105 Proper case windows
  news/3104.bugfix
  pipenv/project.py
  tests/integration/test_windows.py
Labels: regression, windows

#3225 Fix encoding issues and python discovery
  .azure-pipelines/steps/run-tests.yml
  news/3223.bugfix.rst
  news/3224.bugfix.rst
  pipenv/_compat.py
  pipenv/cli/command.py
  pipenv/environments.py
  pipenv/vendor/pythonfinder/models/python.py
Labels: regression, vendored dependencies

#3120 Consolidate all contributing docs in the rst file
  CONTRIBUTING.md
  docs/dev/contributing.rst
Labels: ready to merge

#3251 Redirect all spinner output to stderr
  news/3239.bugfix.rst
  pipenv/core.py
  pipenv/environment.py
  pipenv/utils.py
  pipenv/vendor/vistir/contextmanagers.py
  pipenv/vendor/vistir/misc.py
  pipenv/vendor/vistir/spin.py
Labels: vendored dependencies

#3256 Fix parsing of named `setup.py` extras
  news/3230.bugfix.rst
  pipenv/vendor/requirementslib/models/setup_info.py
Labels: dependency resolution, vendored dependencies

#3268 Ignore hashes when using `--skip-lock`
  news/3255.bugfix.rst
  pipenv/core.py
  pipenv/project.py
  pipenv/utils.py
  pipenv/vendor/plette/__init__.py
  pipenv/vendor/plette/models/base.py
  pipenv/vendor/requirementslib/__init__.py
  pipenv/vendor/requirementslib/environment.py
  pipenv/vendor/requirementslib/models/pipfile.py
  pipenv/vendor/requirementslib/models/requirements.py
  pipenv/vendor/requirementslib/models/setup_info.py
  pipenv/vendor/vendor.txt
Labels: tests

#3280 Feature/update vendored deps
  .azure-pipelines/jobs/run-manifest-check.yml
  news/3280.vendor.rst
  pipenv/vendor/pythonfinder/models/path.py
  pipenv/vendor/pythonfinder/models/python.py
  pipenv/vendor/pythonfinder/utils.py
  pipenv/vendor/vendor.txt
  pipenv/vendor/vistir/__init__.py
  pipenv/vendor/vistir/compat.py
  pipenv/vendor/vistir/misc.py
  pipenv/vendor/vistir/path.py
  pipenv/vendor/vistir/spin.py
  pipenv/vendor/vistir/termcolors.py
Labels: vendored dependencies
