Repository pypa/pipenv, pull requests merged in 2018-08, with the labels that each got.

#2674 Add link to PEP-440 version specifiers in documentation
  docs/basics.rst
Labels: documentation, needs news, ready to merge

#2688 Add test for setup.py::dependency-link field
  tests/integration/test_install_twists.py
Labels: ready to merge, tests, vcs

#2671 Update basics.rst with `$SHELL`.
  docs/basics.rst
Labels: documentation, ready to merge

#2702 Added an example to README.md for installing from git
  README.md
  news/2685.doc
Labels: documentation, needs news, ready to merge

#2696 Improves message when dependencies could not be resolved.
  pipenv/utils.py
Labels: needs news

#2758 Warning for non-existent PIPENV_DOTENV_LOCATION file
  news/2754.trivial
  pipenv/core.py
  tests/unit/test_core.py
Labels: enhancement, ready to merge

#2762 Best practice proposal: do not recommend --system for a Docker context
  docs/advanced.rst
  news/2762.doc
Labels: documentation, ready to merge
