Repository pypa/pipenv, pull requests merged in 2018-06, with the labels that each got.

#2315 Refactor and cleanup some locking code
  pipenv/core.py
  pipenv/utils.py
Labels: ready to merge

#2287 Cleaner shell history
  pipenv/core.py
Labels: ready to merge

#2356 Use Path.touch to better ensure file existence
  pipenv/project.py
Labels: bug 🐛

#2379 Switch all update workflows to `pipenv lock/sync`
  pipenv/cli.py
  pipenv/core.py
  tests/integration/test_pipenv.py
Labels: ready to merge

#2385 Use shell=False when "run" if possible on Windows
  news/2385.feature
  pipenv/core.py
Labels: enhancement, windows

#2422 Install Jinja2 templates for click_completion
  setup.py
Labels: ready to merge

#2415 Allow virtual env creation in dir with leading dash
  pipenv/core.py
  tests/integration/test_pipenv.py
Labels: ready to merge

#2427 prettytoml: Catch StopIteration in AbstractTable._enumerate_items
  news/2426.vendor
  tasks/vendoring/patches/patched/_post-pip-update-pep425tags.patch
  tasks/vendoring/patches/patched/prettytoml-python37.patch
Labels: ready to merge, vendored dependencies

#2433 Update requirementslib to fix #2421
  news/2433.bugfix
  news/2433.vendor
  pipenv/vendor/requirementslib/__init__.py
  pipenv/vendor/requirementslib/models/requirements.py
  pipenv/vendor/vendor.txt
  tests/integration/test_install_uri.py
Labels: vendored dependencies
