Repository pypa/pipenv, pull requests merged in 2019-06, with the labels that each got.

#3738 Allows overriding `PIP_EXISTS_ACTION` environment variable (it was forced to `w`)
  news/3738.feature.rst
  pipenv/core.py
  pipenv/environments.py
Labels: Category: Performance, PR: awaiting-merge, Status: Accepted :heavy_check_mark:, Type: Enhancement :bulb:

#3354 Fix pipenv --clear is not working
  news/3353.bugfix
  pipenv/cli/command.py
  tests/integration/test_cli.py
Labels: Type: Maintenance :construction:

#3787 Bugfix/3786
  news/3786.bugfix.rst
  pipenv/utils.py
  pipenv/vendor/requirementslib/models/markers.py
  pipenv/vendor/requirementslib/models/setup_info.py
  pipenv/vendor/requirementslib/models/utils.py
  pipenv/vendor/vistir/misc.py
Labels: Category: Dependency Resolution

#3797 Fix azure pipelines
  .azure-pipelines/docs.yml
  .azure-pipelines/jobs/run-manifest-check.yml
  .azure-pipelines/jobs/run-tests-windows.yml
  .azure-pipelines/jobs/run-tests.yml
  .azure-pipelines/jobs/run-vendor-scripts.yml
  .azure-pipelines/jobs/test.yml
  .azure-pipelines/linux.yml
  .azure-pipelines/steps/create-virtualenv-linux.yml
  .azure-pipelines/steps/create-virtualenv-windows.yml
  .azure-pipelines/steps/reinstall-pythons.yml
  .azure-pipelines/windows.yml
  azure-pipelines.yml
Labels: Category: Tests, Type: Maintenance :construction:
