Repository pypa/pipenv, pull requests merged in 2019-05, with the labels that each got.

#3745 make check unused work
  news/3745.bugfix.rst
  pipenv/core.py
  tests/integration/test_cli.py
Labels: Category: Tests, PR: awaiting-merge, Type: Bugfix

#3675 Remove unused vendored blindspin
  news/3640.trivial.rst
  pipenv/vendor/blindspin/LICENSE
  pipenv/vendor/blindspin/__init__.py
  pipenv/vendor/vendor.txt
  tasks/vendoring/__init__.py
Labels: Category: Tests, PR: reviewed, Type: Maintenance :construction:, Type: Vendored Dependencies

#3669 conftest.py: Ignore KeyboardInterrupt
  news/3669.trivial.rst
  tests/integration/conftest.py
Labels: Category: Tests, Priority: Low

#3676 Remove unused vendored shutilwhich
  news/3621.trivial.rst
  pipenv/vendor/shutilwhich/LICENSE
  pipenv/vendor/shutilwhich/__init__.py
  pipenv/vendor/shutilwhich/lib.py
  pipenv/vendor/vendor.txt
  tasks/vendoring/__init__.py
Labels: Category: Tests, PR: awaiting-merge, Priority: Low, Type: Maintenance :construction:, Type: Vendored Dependencies

#3684 Remove always-True if-statement, and make function docstring accurate
  news/3684.trivial.rst
  pipenv/utils.py
Labels: PR: awaiting-news, PR: reviewed, Priority: Low, Status: Changes Requested

#3528 Ensure docs show nav on small-screen devices
  docs/_templates/hacks.html
  news/3527.doc.rst
Labels: Status: Accepted :heavy_check_mark:, Type: Documentation :book:

#3408 Prevent a crash in version check error message
  pipenv/core.py
Labels: Priority: Low, Status: Accepted :heavy_check_mark:, Status: Rebase Required, Type: Bugfix

#3753 Update core.py
  news/3753.trivial.rst
  pipenv/core.py
Labels: PR: awaiting-merge, Priority: Low, Status: Awaiting Update :hourglass_flowing_sand:, Type: Documentation :book:

#3479 add test for counting pre option and fix it's duplicate
  news/3479.bugfix.rst
  pipenv/cli/options.py
  tests/unit/test_help.py
Labels: Category: CLI, Category: Tests

#3759 Doc: advanced.rst: Use "pytest" as the new recommended entrypoint for…
  docs/advanced.rst
  news/3759.doc.rst
Labels: Priority: Low, Status: Accepted :heavy_check_mark:, Status: Awaiting Update :hourglass_flowing_sand:, Type: Documentation :book:

#3768 Fix keyerror in keep_outdated when using VCS dependencies
  news/3768.bugfix.rst
  pipenv/resolver.py
  pipenv/utils.py
  pipenv/vendor/requirementslib/models/requirements.py
  pipenv/vendor/requirementslib/models/setup_info.py
  setup.py
Labels: Category: Dependency Resolution, Category: VCS

#3728 fixed broken link for diagnose documentation
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: Category: Development, Priority: Low, Status: Awaiting Update :hourglass_flowing_sand:, Type: Documentation :book:

#2966 #2317 documentation variable expansion
  docs/advanced.rst
  news/2317.doc.rst
Labels: Priority: Low, Status: In Progress, Type: Documentation :book:

#3661 Add new feature toggle for VCS dependency resolution
  .azure-pipelines/steps/run-tests-linux.yml
  .azure-pipelines/steps/run-tests-windows.yml
  .azure-pipelines/steps/run-tests.yml
  .azure-pipelines/steps/run-vendor-scripts.yml
  Pipfile.lock
  news/3577.feature.rst
  news/3647.bugfix.rst
  news/3656.bugfix.rst
  pipenv/core.py
  pipenv/environments.py
  pipenv/patched/piptools/utils.py
  pipenv/resolver.py
  pipenv/utils.py
  pipenv/vendor/vistir/compat.py
  pipenv/vendor/vistir/misc.py
  tasks/vendoring/patches/patched/piptools.patch
  tests/integration/test_lock.py
Labels: Category: Dependency Resolution, Priority: High, Status: In Progress, Type: Enhancement :bulb:, Type: Release Blocker
