Repository pypa/pipenv, pull requests merged in 2019-03, with the labels that each got.

#3585 Bugfix 3584
  news/3584.bugfix.rst
  pipenv/project.py
Labels: ready to merge

#3562 Update pytest-pypi documentation not to be pytest-httpbin documentation
  news/3292.trivial.rst
  tests/pytest-pypi/DESCRIPTION.rst
  tests/pytest-pypi/README.md
  tests/pytest-pypi/setup.py
Labels: ready to merge, vendored dependencies

#3556 bugfix/3502 trusted host fails with custom port
  news/3502.bugfix.rst
  pipenv/utils.py
  tests/unit/test_utils.py
Labels: ready to merge

#3536 Removing my testimonial
  docs/index.rst
Labels: ready to merge

#3532 docs: code option clarification
  pipenv/cli/options.py
Labels: ready to merge

#3601 Port #3263 with updates
  pipenv/cli/command.py
Labels: PR: awaiting-merge, Type: Enhancement :bulb:

#3643 added the TOML Spec link to the documentation
  docs/basics.rst
  news/3629.doc.rst
Labels: PR: awaiting-merge, PR: reviewed, Type: Documentation :book:

#3304 Full implementation of `--keep-outdated`
  .azure-pipelines/jobs/test.yml
  Pipfile
  Pipfile.lock
  peeps/PEEP-005.md
  pipenv/core.py
  pipenv/environment.py
  pipenv/exceptions.py
  pipenv/resolver.py
  pipenv/utils.py
  tests/integration/test_lock.py
Labels: Category: Dependency Resolution, Status: Accepted :heavy_check_mark:, Type: Bugfix, Type: Release Blocker

#3645 Avoid using requests in tests
  tests/integration/test_install_markers.py
Labels: Category: Tests, Status: Accepted :heavy_check_mark:

#3555 Add FreeBSD installation instructions
  README.md
Labels: PR: awaiting-merge
