Repository pypa/pipenv, pull requests merged in 2019-07, with the labels that each got.

#3758 Adds info on env variables
  docs/advanced.rst
Labels: PR: awaiting-merge, Type: Documentation :book:

#3843 Make sure symlinks are resolved.
  news/3842.bugfix.rst
  pipenv/project.py
Labels: Type: Maintenance :construction:

#3246 Update manual
  CONTRIBUTING.md
  docs/advanced.rst
  docs/basics.rst
  docs/dev/contributing.rst
  docs/install.rst
  news/3120.doc.rst
  news/3246.doc.rst
  pipenv/cli/command.py
  pipenv/pipenv.1
  tasks/release.py
Labels: Category: Development, PR: reviewed, Priority: Low, Status: Accepted :heavy_check_mark:, Type: Documentation :book:

#3836 Ensure we always respect --site-packages
  news/3718.bugfix.rst
  pipenv/cli/command.py
  pipenv/cli/options.py
  pipenv/core.py
  pipenv/vendor/requirementslib/models/setup_info.py
Labels: Category: CLI, Priority: Medium, Type: Bugfix

#3844 run: re-enable --help option
  news/3844.behavior.rst
  pipenv/cli/command.py
Labels: Category: CLI, PR: awaiting-merge, Type: Bugfix

#3847 Eliminate duplicate error outputs.
  pipenv/core.py
Labels: Category: CLI, Category: Error Handling, Type: Bugfix, Type: Maintenance :construction:

#3853 Update vendor packages
  news/3807.bugfix.rst
  pipenv/vendor/pythonfinder/utils.py
  pipenv/vendor/requirementslib/models/setup_info.py
  pipenv/vendor/requirementslib/models/utils.py
  tasks/release.py
Labels: Category: Development, Type: Maintenance :construction:, Type: Vendored Dependencies

#3869 Update virtualenv
  Pipfile.lock
Labels: Category: Development, Type: Maintenance :construction:

#3868 Touch up sidebar
  docs/_templates/sidebarintro.html
Labels: PR: awaiting-merge
