Repository pypa/pipenv, pull requests merged in 2020-04, with the labels that each got.

#3878 PEEP: new behavior of `pipenv lock -r -d`
  peeps/PEEP-006.md
Labels: Status: Requires Approval

#4167 Replace docs.pipenv.org with pipenv.pypa.io
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  CONTRIBUTING.md
  docs/dev/contributing.rst
  news/4167.doc.rst
  pipenv/cli/command.py
Labels: PR: awaiting-merge, Type: Documentation :book:

#4129 Fix locking of sub-dependencies for dependencies from VCS
  pipenv/environments.py
Labels: Category: Dependency Resolution, Category: VCS, PR: awaiting-merge

#4200 `pipenv lock -r` respect pypi_mirror args
  news/4199.behavior.rst
  pipenv/core.py
  tests/integration/test_lock.py
Labels: Category: Dependency Resolution, Category: Private PyPIs :sunglasses:, Priority: Low, Status: Changes Requested, Type: Enhancement :bulb:, good first issue

#4206 Add general installation info
  README.md
Labels: Type: Documentation :book:, good first issue

#4208 Automate release workflow
  .github/workflows/pypi_upload.yml
  Pipfile.lock
  RELEASING.md
  pipenv/core.py
  tasks/release.py
Labels: Category: Development, PR: awaiting-review, Priority: High, Type: Enhancement :bulb:, Type: Maintenance :construction:

#3472 Added --db, --output, and --squelch flags. Cleaned up duplicate code.
  peeps/PEEP-044.md
  pipenv/cli/command.py
  pipenv/core.py
Labels: Category: CLI, PR: reviewed, Type: API Change, Type: Enhancement :bulb:

#4211 fix(pep425tags): missing `os` package import added
  pipenv/patched/notpip/_internal/pep425tags.py
  tasks/vendoring/patches/patched/_post-pip-update-pep425tags.patch
Labels: PR: reviewed, Priority: Critical, Type: Bugfix, Type: Release Blocker

#4209 Add sphinx spellcheck addon
  CHANGELOG.rst
  Pipfile
  Pipfile.lock
  RELEASING.md
  docs/advanced.rst
  docs/conf.py
  docs/dev/contributing.rst
  docs/dev/philosophy.rst
  docs/diagnose.rst
  docs/index.rst
  docs/install.rst
  docs/spelling_wordlist.txt
  news/4209.doc.rst
  pipenv/cli/command.py
  pipenv/cli/options.py
  pipenv/environments.py
Labels: Type: Documentation :book:
