Repository pypa/pipenv, pull requests merged in 2022-02, with the labels that each got.

#4944 improve detection of CI
  news/4944.bugfix.mdB
  pipenv/environments.py
Labels: Category: Development, Status: Accepted :heavy_check_mark:

#4103 Improve wording in "basics.rst"
  docs/basics.rst
Labels: Type: Documentation :book:, PR: reviewed, Status: Rebase Required

#4955 Windows: locate pyenv from PATH correctly
  pipenv/utils.py
  tests/unit/test_utils_windows_executable.py
Labels: OS: Windows

#4797 Use PIPENV_SKIP_LOCK environment variable
  news/4797.feature.rst
  pipenv/environments.py
Labels: Status: Accepted :heavy_check_mark:
