Repository pypa/pipenv, pull requests merged in 2022-10, with the labels that each got.

#5380 Prefer to use the lockfile sources if available since this is used in install phase
  news/5380.bugfix.rst
  pipenv/utils/indexes.py
Labels: hacktoberfest, hacktoberfest-accepted

#5386 Bump dparse version to 0.6.2
  pipenv/vendor/dparse/__init__.py
  pipenv/vendor/dparse/dependencies.py
  pipenv/vendor/dparse/errors.py
  pipenv/vendor/dparse/filetypes.py
  pipenv/vendor/dparse/parser.py
  pipenv/vendor/dparse/regex.py
  pipenv/vendor/dparse/updater.py
  pipenv/vendor/vendor.txt
  tasks/vendoring/patches/vendor/dparse-local-yaml.patch
  tests/integration/conftest.py
Labels: hacktoberfest-accepted

#5384 Vendor latest wheel
  pipenv/patched/pip/_vendor/pkg_resources/LICENSE
  pipenv/vendor/vendor.txt
  pipenv/vendor/wheel/__init__.py
  pipenv/vendor/wheel/cli/pack.py
  pipenv/vendor/wheel/macosx_libfile.py
  pipenv/vendor/wheel/vendored/packaging/tags.py
  pipenv/vendor/wheel/wheelfile.py
Labels: hacktoberfest-accepted

#5381 Add news fragment for dropping six
  news/5187.vendor.rst
Labels: hacktoberfest, hacktoberfest-accepted

#5383 Update documentation around requirements command and provide current examples.
  docs/advanced.rst
Labels: hacktoberfest

#5388 Add pytest.markers to pyproject.toml
  news/5388.dev.process.rst
  pyproject.toml
Labels: hacktoberfest, hacktoberfest-accepted

#5387 Python full version in pipfile
  news/5345.behavior.rst
  pipenv/project.py
  tests/integration/test_install_basic.py
Labels: hacktoberfest, hacktoberfest-accepted

#5366 Support Named Package Categories
  Pipfile
  Pipfile.lock
  docs/basics.rst
  pipenv/cli/command.py
  pipenv/cli/options.py
  pipenv/core.py
  pipenv/environment.py
  pipenv/project.py
  pipenv/resolver.py
  pipenv/utils/dependencies.py
  pipenv/utils/resolver.py
  pipenv/utils/toml.py
  pipenv/vendor/plette/lockfiles.py
  pipenv/vendor/plette/pipfiles.py
  pipenv/vendor/requirementslib/models/lockfile.py
  pipenv/vendor/requirementslib/models/pipfile.py
  pipenv/vendor/requirementslib/models/project.py
  tasks/vendoring/__init__.py
  tests/integration/test_install_basic.py
  tests/integration/test_install_categories.py
  tests/integration/test_install_markers.py
  tests/integration/test_install_twists.py
  tests/integration/test_lock.py
  tests/integration/test_project.py
  tests/integration/test_uninstall.py
Labels: hacktoberfest, hacktoberfest-accepted

#5396 Update documentation for callable scripts
  docs/advanced.rst
  news/5396.doc.rst
  pipenv/cmdparse.py
Labels: hacktoberfest, hacktoberfest-accepted

#5400 Remove recommended packages link in doc sidebar
  docs/_templates/sidebarlogo.html
Labels: hacktoberfest, hacktoberfest-accepted

#5412 Update Link For VCS Support
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#5410 Add missing backtick in the contributing documentation.
  docs/dev/contributing.rst
Labels: hacktoberfest, hacktoberfest-accepted
